# Generated by Django 5.0.4 on 2024-04-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anaween', '0002_alter_enwaan_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enwaan',
            old_name='name',
            new_name='الأسم',
        ),
        migrations.RenameField(
            model_name='enwaan',
            old_name='phone',
            new_name='الرقم',
        ),
        migrations.RenameField(
            model_name='enwaan',
            old_name='address',
            new_name='العنوان',
        ),
    ]
