# Generated by Django 4.2.11 on 2024-04-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anaween', '0005_enwaan_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enwaan',
            old_name='الأسم',
            new_name='الأسم_والمنطقة',
        ),
    ]
