# Generated by Django 4.2.11 on 2024-04-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anaween', '0006_rename_الأسم_enwaan_الأسم_والمنطقة'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enwaan',
            name='الرقم',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
