# Generated by Django 4.2.11 on 2024-04-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anaween', '0008_useredit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEdit',
        ),
    ]
