# Generated by Django 4.2.11 on 2024-04-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anaween', '0009_delete_useredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='enwaan',
            name='مقاطعة',
            field=models.BooleanField(default=False),
        ),
    ]
