# Generated by Django 4.2.11 on 2024-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anaween', '0011_enwaan_الوصف'),
    ]

    operations = [
        migrations.AddField(
            model_name='enwaan',
            name='text',
            field=models.CharField(default='لا', max_length=255),
        ),
    ]
